# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GohuPN6BdyozS97iwWQgW8q8BallvzJ6
"""

!pip install qiskit

!pip install qiskit[visualization] qiskit-aer --quiet

from qiskit import QuantumCircuit
from qiskit_aer import Aer
from qiskit.visualization import plot_histogram

import matplotlib.pyplot as plt

def deutsch_oracle(is_constant=True):
    oracle = QuantumCircuit(2)
    if is_constant:
        pass
    else:
        oracle.cx(0,1)

    return oracle

def deutsch_circuit(is_constant=True):
    qc = QuantumCircuit(2,1)

    qc.x(1)
    qc.h(0)
    qc.h(1)

    if is_constant:
      pass  
    else:
      qc.cx(0, 1)  




    qc.h(0)
    qc.measure(0,0)
    return qc

def run_deutsch(is_constant=True):
    qc = deutsch_circuit(is_constant)
    simulator = Aer.get_backend("qasm_simulator")


    result = simulator.run(qc, shots=1024, basis_gates=['u1', 'u2', 'u3', 'cx', 'id']).result()

    counts = result.get_counts()

    print("Result (is_constant =", is_constant, "):", counts)
    plot_histogram(counts)
    plt.show()
run_deutsch(is_constant=True)
run_deutsch(is_constant=False)



